name: CI

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache NPM
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install
        run: npm ci

  build:
    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
    needs: install
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache NPM
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
        timeout-minutes: 5
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy Build
        run: |
        zip -r build.zip public
        aws s3 cp build.zip s3://take-me-apart/${{ github.sha }}
